### ISSUE TITLE
Enable logging in JSON

### ISSUE THREAD

**Issue by eze-kiel** [eze-kiel/uptimerobot-exporter#2]
Logging should be done in JSON in order to use Loki with the exporter

**Comment by eze-kiel** [comment]
the zerolog package is an interesting solution

**Comment by krishnaindani** [comment]
I this issue open to working for? I would like to check if I can work on it.

**Comment by eze-kiel** [comment]
of course ! :)

the idea is just to replace logrus by [zerolog](https://github.com/rs/zerolog), and use it to log in a JSON format (with classic logger stuff, such as a flag to choose log level, etc...).

I planned to work on it tomorrow, but if you are interested in resolving it, I can wait! :)

**Comment by krishnaindani** [comment]
Don't plan to take it if you already decided though. BTW logrus also supports JSON logging, not sure if you have seen that.

**Comment by eze-kiel** [comment]
It's a side project, so no worries.

I know about JSON format with logrus, however it is in maintenance mode, and zerolog have some interesting features and is performing well. Also, I'm used to use zerolog on bigger projects :)

But if you feel that logrus is an adequate choice, you can go for it, the important part is the JSON format, not the library :)

**Comment by krishnaindani** [comment]
well, I have not played with zerolog. I will play around with that for this issue. Since you are mentioning the logrus is in maintenance mode, it will be better to use zero log which is actively maintained.

**Comment by krishnaindani** [comment]
Well since we will be allowing the user to pass the log level, is the `log-level command-line argument sounds good? Also, zerolog supports like 7 levels, do we want to support all of those for the user to pass?

```
panic (zerolog.PanicLevel, 5)
fatal (zerolog.FatalLevel, 4)
error (zerolog.ErrorLevel, 3)
warn (zerolog.WarnLevel, 2)
info (zerolog.InfoLevel, 1)
debug (zerolog.DebugLevel, 0)
trace (zerolog.TraceLevel, -1)
```

**Comment by eze-kiel** [comment]
`log-level` sounds good to me.
String argument seems to be the perfect solution (much easier to remember than an int). The fallback can be avoided by specifying a default value in the flag definition (see how I did for the `a.adress` or `a.port` values at the top of the `main()` function). Moreover, zerolog provides a function called [`ParseLevel`]( https://pkg.go.dev/github.com/rs/zerolog?utm_source=godoc#ParseLevel) that does all the magic for us. 

Maybe we can imagine that if this function returns an error (the user provided a wrong string), we can keep the default value as the log level (info for example) ? This also allows us to use all the 7 log levels without writing too much code.

**Comment by krishnaindani** [comment]
> ParseLevel



> `log-level` sounds good to me.
> String argument seems to be the perfect solution (much easier to remember than an int). The fallback can be avoided by specifying a default value in the flag definition (see how I did for the `a.adress` or `a.port` values at the top of the `main()` 
function). 

yeah by fallback I meant to say providing default in the flag. 

Moreover, zerolog provides a function called [`ParseLevel`](https://pkg.go.dev/github.com/rs/zerolog?utm_source=godoc#ParseLevel) that does all the magic for us.
>

This is great, will take a look at that function.
 
> Maybe we can imagine that if this function returns an error (the user provided a wrong string), we can keep the default value as the log level (info for example) ? This also allows us to use all the 7 log levels without writing too much code.

yup, that sounds great.

**Comment by krishnaindani** [comment]
I have created a pr https://github.com/eze-kiel/uptimerobot-exporter/pull/3.
let me know what do you think.
