### ISSUE TITLE
Still export targets after deletion

### ISSUE THREAD

**Issue by Cleming** [eze-kiel/uptimerobot-exporter#5]
After target deletion in Uptime Robot, uptimerobot-exporter still export targets with last known values.

**Comment by eze-kiel** [comment]
That's an interesting case, thanks for the report! I'll investigate

**Comment by eze-kiel** [comment]
closed by #10

**Comment by eze-kiel** [comment]
@Cleming please note that the new docker images are pushed on GHCR, the latest being `ghcr.io/eze-kiel/uptimerobot-exporter:latest` or for pinned version `ghcr.io/eze-kiel/uptimerobot-exporter:v0.4.3`.
